<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>legend_Login</name>
   <tag></tag>
   <elementGuidId>01462598-c449-4afa-9112-e5ef143e8f2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>legend.w-auto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login-form']/fieldset/legend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>legend</value>
      <webElementGuid>d704046b-ae5b-443a-ad09-e9dc42f69f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-auto</value>
      <webElementGuid>1c114957-1371-43f2-a4ea-dab68c867a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                
                                Login
                            </value>
      <webElementGuid>3a551a8b-dbe4-48e6-a3e0-5a59c46bcbd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form&quot;)/fieldset[@class=&quot;border p-2&quot;]/legend[@class=&quot;w-auto&quot;]</value>
      <webElementGuid>9da7f7ca-30a6-4f54-92e0-4053567e4ce0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/fieldset/legend</value>
      <webElementGuid>0d14ecad-efd9-46e7-abb2-15b66b06958b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username:'])[1]/preceding::legend[1]</value>
      <webElementGuid>308e9a37-5587-4261-8baa-c4978ee63c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password:'])[1]/preceding::legend[1]</value>
      <webElementGuid>760ebad6-92e3-4efc-b428-cbd20da96805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//legend</value>
      <webElementGuid>668ee798-c011-48ab-9c7e-62a07b0cae9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//legend[(text() = '
                                
                                Login
                            ' or . = '
                                
                                Login
                            ')]</value>
      <webElementGuid>5f920e68-ab81-42bd-be8a-7451fa0fee72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
