<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(What, , s the patient phone nu_867169</name>
   <tag></tag>
   <elementGuidId>e0b7f6bb-6844-45f2-b3d3-2fc7eed82c38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fr3483-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'phoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff9145c2-92d7-4cbd-b729-20c3bd1f4523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed76ad14-397b-4f92-bf6f-35c0fe3c038d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fr3483-field</value>
      <webElementGuid>dda1811f-6663-4439-828e-256a6b7ad11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>085ca339-46fe-4497-b1de-af68f74b743e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phone focused</value>
      <webElementGuid>889c28f1-5cf6-44f7-9955-ecc6d6aa7b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fr3483-field&quot;)</value>
      <webElementGuid>550a4c72-9dd8-4f1d-ab5f-fca698a198b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fr3483-field']</value>
      <webElementGuid>f830b5fd-a0b6-48bb-be9a-c2b32a6878ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='phoneNumberLabel']/p/input</value>
      <webElementGuid>1184cee6-8356-4433-87ca-ab50a179fb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/p/input</value>
      <webElementGuid>19835fa5-a575-449b-9cd3-4215cf81e149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fr3483-field' and @name = 'phoneNumber']</value>
      <webElementGuid>c7d6e42c-ee53-482f-81b7-1cad3238e1ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
