<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(required)_birthdateDay</name>
   <tag></tag>
   <elementGuidId>a2ab5783-f4d2-48fb-a3ce-53ce93064c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#birthdateDay-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'birthdateDay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d5221aa-21bf-46df-a285-caac298b1428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed8f5f37-0273-4430-8df4-609bb5af36d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthdateDay-field</value>
      <webElementGuid>21846291-2698-4131-8aaf-eddedb6ec1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthdateDay</value>
      <webElementGuid>ae2f7ab7-624f-443c-a921-a53537cfd56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>day number numeric-range date-component requiredTitle focused</value>
      <webElementGuid>fc806ec5-81f1-42ec-b019-d2b710f9427b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>401d8572-6a23-4c08-8168-49eb632bbd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>20458436-8633-439a-bc73-3a90f8cabfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fb4fbe13-bf04-4d20-bca7-58792762dd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>d4da6628-aa32-48bd-bef9-c88a7aa7860c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthdateDay-field&quot;)</value>
      <webElementGuid>d6f273f3-587e-4c5c-b00e-c5d809ebdfdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthdateDay-field']</value>
      <webElementGuid>ccac0510-3dc0-4028-8916-b7ef2689d6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='demographics-birthdate']/p[2]/input</value>
      <webElementGuid>7dce6598-1d2b-4050-95cc-ff097ab51cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/p[2]/input</value>
      <webElementGuid>15fc02e7-f47f-40e4-8925-d75e4a21be17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'birthdateDay-field' and @name = 'birthdateDay']</value>
      <webElementGuid>7101f783-0d92-43ae-8694-269475c5e399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
