<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(required)_birthdateYear</name>
   <tag></tag>
   <elementGuidId>f066bc1d-4729-47e3-b601-3e9bd6512a85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#birthdateYear-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthdateYear-field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67d345aa-2d5e-4737-8fcb-03c5eeeb3b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2822dff7-f5d0-4577-bcb6-9e25d59c7d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthdateYear-field</value>
      <webElementGuid>851b6102-d279-4591-ae36-0d5038912946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthdateYear</value>
      <webElementGuid>26c118d2-f700-44da-b777-5ca5cd5ea34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>year number numeric-range date-component requiredTitle focused</value>
      <webElementGuid>6a3d8cc5-4d25-40f3-96af-f07223659846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>73cf1de8-328c-412e-9246-c73289022e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>2fe868e9-3097-4822-8e88-da2b7878504d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1903</value>
      <webElementGuid>af5a5230-0ce2-4e3d-9361-a1e2b7e91a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2023</value>
      <webElementGuid>62b33769-80d9-4d1e-9564-8eaa1db96252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthdateYear-field&quot;)</value>
      <webElementGuid>c90c48cd-5650-4146-953b-dba305d43a6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthdateYear-field']</value>
      <webElementGuid>aadac569-900b-43c1-8d9d-b08db79e17c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='demographics-birthdate']/p[4]/input</value>
      <webElementGuid>c6739494-c244-41d2-9780-c445daa3dd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/input</value>
      <webElementGuid>862bed58-9635-470c-83d2-874ab8ab93ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'birthdateYear-field' and @name = 'birthdateYear']</value>
      <webElementGuid>da58551a-6677-453b-abc1-d0624b318617</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
