<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(required)_familyName</name>
   <tag></tag>
   <elementGuidId>2c3bae8c-4771-42b0-9a65-5072a725f930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fr1500-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'familyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb8c1997-a043-41ee-8179-c02f27f3692c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>96dcde8e-40d3-4e1d-8633-91b27ad75180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fr1500-field</value>
      <webElementGuid>e36bb316-a714-47d0-81a3-22d37b895134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>familyName</value>
      <webElementGuid>9aa17ca7-a13b-43fd-913e-36c9d49ddf17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required ui-autocomplete-input</value>
      <webElementGuid>c94348eb-853d-4a69-b846-b11fb16719f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e4c8c79d-33cb-412f-97af-24486bff28aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fr1500-field&quot;)</value>
      <webElementGuid>26b868d1-d5f5-4b06-9386-9af4f5fe3d16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fr1500-field']</value>
      <webElementGuid>0ddb86df-5a46-4751-9b7f-a3c0739dbff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='demographics-name']/div/p[3]/input</value>
      <webElementGuid>1d1a6828-bbf2-4a74-9c09-2310c48b1218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/input</value>
      <webElementGuid>2ebd24a8-9313-428e-b8ba-6e2d1aff731e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fr1500-field' and @name = 'familyName']</value>
      <webElementGuid>05c5458c-d2dc-4263-9201-bc71d77a1215</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
