<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(required)_givenName</name>
   <tag></tag>
   <elementGuidId>8f69c66a-11ac-46b1-b18f-0e751008d839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fr2010-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'givenName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5e549d7-bd93-4600-b97e-a0b8a5b8e0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97d735fe-da09-4115-b786-012af3953782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fr2010-field</value>
      <webElementGuid>cdb2c48d-95d8-453b-995b-79ffd8b9e2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>givenName</value>
      <webElementGuid>3207b37c-418e-4a90-8a05-a0be957a2992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required focused ui-autocomplete-input</value>
      <webElementGuid>86f4d8e6-72ac-4e48-b76d-dbf8552bf1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0e364da1-460f-4916-b932-6c080564d7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fr2010-field&quot;)</value>
      <webElementGuid>a805d891-cf17-4535-a693-4fe10f50b6f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fr2010-field']</value>
      <webElementGuid>9efd03e3-4ebf-48b4-a9e5-2eabc51941b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='demographics-name']/div/p/input</value>
      <webElementGuid>510ce624-85b6-471e-b7a2-b4e71a941927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4e446e4b-79ab-4686-8c9a-b3cdd6989405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fr2010-field' and @name = 'givenName']</value>
      <webElementGuid>b5c93935-4021-4bad-be64-d02bc847afc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
