<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Who is the patient related to_person-_c8514e</name>
   <tag></tag>
   <elementGuidId>903a6a6c-b839-4906-bd0c-6131d3334abe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.person-typeahead.ng-pristine.ng-untouched.ng-valid.ng-empty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e627059-30ca-40dd-86e4-86f84cbad400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef5613a4-edad-4438-804f-fb74de656210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>person-typeahead ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>6428cf9b-de44-41a8-ab9d-1d7f62cee480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Person Name</value>
      <webElementGuid>11b74d33-b548-4e20-9447-2c4f82f02881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>relationship.name</value>
      <webElementGuid>3229c5d9-2c8e-43d3-9ad5-0a676d1ee7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead</name>
      <type>Main</type>
      <value>person as person.display for person in getPersons($viewValue) | limitTo:5</value>
      <webElementGuid>f6a00349-de4f-4579-9c99-acaed55c2c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-min-length</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>83b43506-8a2d-4029-96df-87f327ba16c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-on-select</name>
      <type>Main</type>
      <value>selectPerson($item, $index)</value>
      <webElementGuid>bd885cca-dd19-4763-b96d-1456e79a1133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;relationship&quot;)/p[@class=&quot;left&quot;]/input[@class=&quot;person-typeahead ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>3a73b3f4-f199-476b-85fa-922249be933b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[15]</value>
      <webElementGuid>67577da8-c9db-4aa5-99b7-8e3d01b90aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='relationship']/p[2]/input</value>
      <webElementGuid>d468d61e-aeac-4715-b28e-ee0f563ab20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/p[2]/input</value>
      <webElementGuid>5a2eff88-3434-4b19-98d1-09f190ab43d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Person Name']</value>
      <webElementGuid>1b0f5a82-3013-49e0-9d3e-5333e3a98327</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
